/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package runme;


import io.opentelemetry.instrumentation.annotations.WithSpan;
import reactor.core.publisher.Mono;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    @WithSpan
    public static void main(String[] args) throws InterruptedException {
 


        int x = 0;
        while(x < 10) {
            System.out.println("Hello World!");
            Thread.sleep(100);
            Another another = new Another();
            Mono<String> s = another.Run();
            s.subscribe(z->System.out.println(z)   );
            x++;
        }
    }
}
